language: php

php:
  - 7.0
  - 7.1

sudo: false

before_script:
  - composer selfupdate
  - travis_wait composer update $COMPOSER_FLAGS --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
