version: '2'

services:
    # API: Nginx
    web:
        image: nginx:stable-alpine
        volumes:
            - ./:/var/www/composer-resolver
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '56789:80'
        depends_on:
            - php-fpm
            - redis

    # API: PHP 7.* with FPM SAPI on Alpine Linux Container
    php-fpm:
        image: php:7-fpm-alpine
        volumes:
            - ./:/var/www/composer-resolver

    # API & Worker communication: Redis
    redis:
        image: redis:3.0-alpine
        ports:
            - '6379:6379'

    # Worker: PHP 7.* with CLI SAPI
    worker:
        image: php:7-cli
        volumes:
            - ./:/var/www/composer-resolver
            - ./docker/php.ini:/usr/local/etc/php/conf.d/composer-resolver.ini
        command: php /var/www/composer-resolver/bin/worker.php
        depends_on:
            - redis
