version: '2'

services:
    # API: Nginx
    web:
        image: toflar/composer-resolver-web:latest
        volumes:
            - ./:/var/www/composer-resolver
        ports:
            - '32772:80'
        depends_on:
            - php-fpm
            - redis

    # API: PHP
    php-fpm:
        image: toflar/composer-resolver-php-fpm:latest
        volumes:
            - ./:/var/www/composer-resolver

    # API & Worker communication: Redis
    redis:
        image: redis:3.0-alpine
        expose:
            - '6379'

    # Worker
    worker:
        image: toflar/composer-resolver-worker:latest
        volumes:
            - composer-cache:/var/composer-cache
            - ./:/var/www/composer-resolver
        environment:
            - COMPOSER_CACHE_DIR=/var/composer-cache
            - COMPOSER_RESOLVER_POLLING_FREQUENCY=5
            - COMPOSER_RESOLVER_TERMINATE_AFTER_RUN=0
        depends_on:
            - redis

# Composer cache which is shared for all workers
volumes:
    composer-cache:
