version: '2'

services:
    # API: Nginx
    web:
        image: toflar/composer-resolver-web:latest
        volumes:
            - ./:/var/www/composer-resolver
        ports:
            - '80'
        depends_on:
            - php-fpm
            - redis

    # API: PHP
    php-fpm:
        image: toflar/composer-resolver-php-fpm:latest
        volumes:
            - ./:/var/www/composer-resolver

    # API & Worker communication: Redis
    redis:
        image: redis:3.0-alpine
        expose:
            - '6379'

    # Worker
    worker:
        image: toflar/composer-resolver-worker:latest
        volumes:
            - ./:/var/www/composer-resolver
        depends_on:
            - redis
