version: '2'

services:
    # API: Nginx
    web:
        build:
            context: ./../
            dockerfile: ./docker/web/Dockerfile
        image: toflar/composer-resolver-web:latest
        labels:
            traefik.port: '433'


    # API: PHP 7.* with FPM SAPI on Alpine Linux Container
    php-fpm:
        build:
            context: ./../
            dockerfile: ./docker/php-fpm/Dockerfile
        image: toflar/composer-resolver-php-fpm:latest

    # API & Worker communication: Redis
    redis:
        image: redis:3.0-alpine

    # Worker: PHP 7.* with CLI SAPI
    worker:
        build:
            context: ./../
            dockerfile: ./docker/worker/Dockerfile
        image: toflar/composer-resolver-worker:latest
        command: php /var/www/composer-resolver/bin/worker.php
        environment:
            - COMPOSER_CACHE_DIR=/var/composer-cache

    # Traefik
    traefik:
        image: traefik:camembert
        ports:
            - '80:80'
            - '8080:8080'
            - '433:433'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - traefik-ssl-certificates:/etc/traefik/acme
        command: --docker --docker.swarmmode --docker.domain=traefik --docker.watch --acme --acme.email=yanick.witschi@terminal42.ch
